# coding: utf-8

"""
    Available REST Services

    Request and Response format is JSON, Request validation is: jakarta validation enhanced with a Framework. Since there are so many ways to do Security. I choose a simple one for this project. The user must put a JWT Token in the request header or in a request cookie (will make the AngularJS folks happy). JWT Tokens copied directly from the site http://jwt.io may not work. Why you ask? On the Windows Platform the Character set gets changed, it is not longer UTF-8, it becomes Cp1252 (Eclipse Project Default). No worries, a Junit Test was made to build Tokens. It is called BuildJwtToken. For Swagger usage, copy the token from the Eclipse project Console instead. The Secret to making the JUnit produce a UTF-8 token is to set the Windows Environment Variable JAVA_TOOL_OPTIONS to value -Dfile.encoding=UTF-8

    The version of the OpenAPI document: 1.0.0
    Contact: jfraser2@yahoo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.notification_controller_api import NotificationControllerApi


class TestNotificationControllerApi(unittest.TestCase):
    """NotificationControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationControllerApi()

    def tearDown(self) -> None:
        pass

    def test_all_notifications(self) -> None:
        """Test case for all_notifications

        """
        pass

    def test_create_notification(self) -> None:
        """Test case for create_notification

        """
        pass

    def test_find_by_notification_id(self) -> None:
        """Test case for find_by_notification_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
